name: 'Create Tag'
description: 'Tag a git commit with a semantic version'
author: 'Nic Cope'
branding:
    icon: git-commit
    color: white
inputs:
  token:
    description: Github Token
    required: true
  version:
    description: 'Version (e.g. v0.1.0)'
    required: true
  message:
    description: 'Tag message'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
